### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by duanchao** [Efterklang/yolov5_manhole_cover#1]
作者你好，非常高兴的看到你分享的井盖识别问题的代码，但是我们在运行过程中存在一些错误，比如No such file or directory：‘best.pt’ 能否帮忙解答一下？

**Comment by Efterklang** [comment]
- 下载权重文件,这里我用的是yolov5x.pt;执行train.py;
- 训练过程中会在`runs/train`里得到best.pt和last.pt
<img width="208" alt="image" src="https://github.com/Efterklang/yolov5_manhole_cover/assets/113397634/099811b6-dbed-4151-96f4-5f07036eed01">
yolov5在detect.py的parse_opt函数中可以配置model的路径,将best.pt放在你指定的路径下就可以了
```python
# detect.py
def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default=ROOT /'best.pt', help='model path(s)') 
```
